### ISSUE TITLE
Is easyrtc possible to combine Temasys WebRTC Plugin?

### ISSUE THREAD

**Issue by prospdragon** [priologic/easyrtc#121]
I'm not sure may I can ask these problems;
I have read that Temasys WebRTC Plugin bring support for webRTC to Desktop versions of Safari and IE.
I have tried it with easyrtc.
But I can't the good result.
So is it possible to combine with Temasys WebRTC Plugin?

**Comment by ziaius** [comment]
I am sure there you are not the only one thinking about this!

**Comment by fbernhard** [comment]
We have successfully added support for the plugin to our easyrtc installation:

Take Teamsys' Adapter.js (https://github.com/Temasys/AdapterJS) and use this instead of the adapter.js code that is included at the top of the "api/easyrtc.js" file. It works great for us.

**Comment by prospdragon** [comment]
I have tested again but still it doesn't works.
I took Teamsys' Adapter.js(exactly publish/adapter.debug.js) and replaced with top of api/easyrtc.js(adapter.js of easyrtc).
When I test with "demo_audio_video_simple.html", it works in Chrome.
In IE, I get "Unspecified error." in 
var rectObject = element.getBoundingClientRect(); of easyrtc.js.

I get same result in other demos of easyrtc.

**Comment by EricDavies** [comment]
I remember seeing the problem before when I tried using a plugin before.
The getBoundingClientRect isn't from the easyrtc.js, it's from the temasys adapter.js that you've inserted into it.

My fuzzy memory is that one of the things you have to do before you use the demos with the temasys plugin is move <script> tag that pulls in easyrtc (and anything that depends on it) to just before the </body>. It makes changes to the DOM body when it gets pulled in, and if the script tag is in the header, the temasys code gets pulled in before body has been defined.

I've just pushed a change to the beta branch that replaces the use of "video.dataset.caller" in easyApp (used by many of the demos). I'm told that the use of dataset was causing problems also, so if you are going to try using demos that use easyApp, then you should pull down the beta branch instead of the master branch of easyrtc.

**Comment by EricDavies** [comment]
rats, lost part of my comment: the rest was:
My fuzzy memory is that one of the things you have to do before you use the demos with the temasys plugin is move the script tag that pulls in easyrtc.js from the <head> section to just before </body>. The temasys plugin rewrites the DOM body when it is run and if it is in the header, the body won't be defined yet.

**Comment by fbernhard** [comment]
I have checked again. Indeed, we had to adopt adapter.js slightly. As Eric writes, Teamsys rewrites the DOM body. Once you pass the new "object" element to "**attachMediaSource**" neither "**element.className**" nor "**element.getBoundingClientRect()**" are available. Here's the diff:

```
841a842,844
>     	if (!element || !element.parentNode) {
>     		return;
>     	}
848a852,854
>           if (classHTML == '') {
>         	  classHTML = (element.attributes && element.attributes['class']) ? 'class="' + element.attributes['class'].value + '" ': '';
>           }
855a862
> 
859c866,877
<           var rectObject = element.getBoundingClientRect();
---
>           var height = "";
>           var width = "";
>           if (element.getBoundingClientRect) {
>         	  var rectObject = element.getBoundingClientRect();
>         	  width = rectObject.width + 'px';
>               height = rectObject.height + 'px';
>           }
>           else if (element.width) {
>         	  width = element.width;
>         	  height = element.height;
>           }
>           
862,863c880,881
<           frag.width = rectObject.width + 'px';
<           frag.height = rectObject.height + 'px';
---
>           frag.width = width;
>           frag.height = height;
```
