### ISSUE TITLE
About haveVideoTrack() function

### ISSUE THREAD

**Issue by prospdragon** [priologic/easyrtc#124]
I found haveVideoTrack function returns wrong value sometimes.
For example, I tested without camera and mic.
(easyrtc.enableVideo(false);  easyrtc.enableAudio(false); )
In this case, haveVideoTrack(remoteId) returns true.

So I saw easyRTC docs.
There says "true if there is an audio track or the browser can't tell us.";
What does it mean "or the browser can't tell us" ?

**Comment by EricDavies** [comment]
When that particular method was written, Firefox didn't expose tracks in webrtc media streams, so you simply couldn't tell what a media stream contained. At the time, it made the most sense to simply assume that audio and video video tracks were present, rather than assume they weren't, if you couldn't tell. 

These days, that case shouldn't ever occur, video and audio tracks are exposed by all browsers that support WebRTC.
