### ISSUE TITLE
EasyRTC js on Apache Cordova PermissionDeniedError

### ISSUE THREAD

**Issue by drpeque** [priologic/easyrtc#131]
Hello.

I would like to integrate easyRTC..js in an app developed on Apache Cordova. If I try to run one of the easyRTC demos we found in github, the result is always. 

     Trying getUserMedia a second time easyrtc.js:1774
     getusermedia failed easyrtc.js:1735
     invoking error callback PermissionDeniedError 

I have put the Manifest permission in Android platform, but the result is still the same.

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.RECORD_VIDEO" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />

However, If I put the same html, and javascript in a remote server and open it from device, video and audio works properly. 
So, the problem is when Cordova try to extract getUserMedia form device. 

Any ideas?
Should I install any cordova plugin?

Thanks.

**Comment by EricDavies** [comment]
Cordova probably doesn't support WebRTC without a plugin.
See the thread: 
https://groups.google.com/forum/?fromgroups#!searchin/discuss-webrtc/webrtc$20cordova/discuss-webrtc/KbJfWJwl1hk/WH9h0-q9oUMJ

**Comment by drpeque** [comment]
Thanks Eric.

I have installed PhoneRTC, demos works properly and the videoConf is good enough in the ionic demo app. I have been working in order to understand how the plugin get the media in order to use PhoneRTC with easyRTC server, because the problem is that you mix two different Signalling Servers with the own methods and messages.

With easyRTC you have a solution for web pages. and if it is possible, the same for andoroid device. So the question is ... how I can use PhoneRTC but with the easyRTC signaaling Server.

Thanks again.

**Comment by EricDavies** [comment]
If you are looking at EasyRTC because of Android, you should be aware 
that we only make our iOS and android client side libraries available 
for large customers. The smaller players can't afford to pay enough to 
fund the support level that would be necessary with native clients.

If PhoneRTC has it's own signalling server, your life is going to be 
simpler sticking to PhoneRTC all the way.

**Comment by drpeque** [comment]
Ok Eric.

Thanks for your answer. 
We would like to find a global solution for Web and mobile devices. So, the idea to use easyRTC.

Thanks.

**Comment by bgawande** [comment]
hello Eric.
i want  to connect android device to web browser using easy rtc......
to add audio and video calling feature to my demo web application running in tomcat server to my local...
web to web communication is working but how to implement android????

**Comment by EricDavies** [comment]
Your easiest approach is to run Chrome on your android device and run 
the same web app.

The alternative is to implement the easyrtc client code in Java, after 
building the android webrtc libraries. Building the android libraries is 
much easier than it used to be (google has a howto at 
https://webrtc.org/native-code/development/ ). But I wouldn't recommend 
it unless you had a very profitable application; maintaining webrtc 
native code is a pain because the APIs are constantly evolving.

Eric.
