### ISSUE TITLE
callFailureCB is undefined

### ISSUE THREAD

**Issue by hthetiot** [priologic/easyrtc#133]
Using IE has a receiver of the call I got the following JS error "callFailureCB is undefined".
Even if IE refuse the call or not.

Following
>   if (!self.supportsPeerConnections()) {
>    callFailureCB(self.errCodes.CALL_ERR, self.getConstantString("noWebrtcSupport"));
>     return;
>  }

Should be:

>   if (!self.supportsPeerConnections()) {
>     easyrtc.showError(self.errCodes.CALL_ERR, self.getConstantString("noWebrtcSupport"));
>     return;
>  }

**Comment by hthetiot** [comment]
The fix I propose is only triggering the "easyrtc.showError" if the env has no supportsPeerConnections and the call is accepted.

**Comment by EricDavies** [comment]
Good catch! Thank you!

I've just pushed a fix onto the beta branch. The only difference I've done from your suggest was to set wasAccepted to false and fall through to sending a reject message instead of returning. This way, the caller isn't left hanging waiting for a response.

I've got a reconnection problem with code on the beta branch at the moment that I haven't figured out yet, so you may want to stick with your solution instead of pulling down the most recent beta for now.

**Comment by hthetiot** [comment]
Thx Eric,
I use my own fork anyway, will watch your branches and sync if i fell it's it worth it.

**Comment by hthetiot** [comment]
I also simply refuse the call on my side if there is no "supportsPeerConnections" on the application side.
