### ISSUE TITLE
only receive audio not possible.

### ISSUE THREAD

**Issue by dharmphp** [priologic/easyrtc#171]
In our application there is one broadcaster and multiple receiving nodes. the receiving nodes will only be able to receive audio, but should not be able to reply, so basically it does not require audio input. but if I disable audio and video and only enable audio receive it's not working. Is there a way to receive audio without asking for microphone?

**Comment by EricDavies** [comment]
The problem is that you are using easyrtc.easyApp which makes certain
assumptions, like that both parties are supplying a media stream.
Try the https://demo.easyrtc.com/demos/demo_audio_video.html demo and
you'll see it's possible.
In general, for such questions, you should be looking on our forum, because
all the common questions have been asked and answered before :-).

**Comment by hthetiot** [comment]
@backbencher Close if you got it work.
