### ISSUE TITLE
facing issue while implementing screen sharing 

### ISSUE THREAD

**Issue by xtreme1397** [priologic/easyrtc#234]
in easyrtc client api documentation i saw there is some method called as easyrtc.initScreenCapture().and it was mentioned there that using this method we can create media stream for desktop sharing.but there is no such method i found inside easyrtc.

**Comment by EricDavies** [comment]
That reference should have been removed. The original screen share support in chrome worked almost but was never production ready. It used too much bandwidth and crashed frequently. I'm not even sure if its still supported by the browser.


What you want to use is initDesktopStream, as done in the multistream iframe demo. The code in that demo looks like:
   screenShareButton.onclick = function() {
        var streamName = ... come up with a name for the stream
        easyrtc.initDesktopStream(
                function(stream) {
                    .... do something with the stream
                },
                function(errCode, errText) {
                    ... handle the error
                },
                streamName);
    };

Google, in its wisdom/paranoia, feels that because being able to read a window (or screen) on the desktop is a potential security hole, anybody who uses the app has to install a chrome extension. The iframe version uses Muaz Khan's universal extension (described at https://www.webrtc-experiment.com/screen-sharing/, installed from https://chrome.google.com/webstore/detail/webrtc-desktop-sharing/nkemblooioekjnpfekmjhpgkackcajhg ). The noniframe version uses a tailored version of the extension. Yes, requiring your users to install an extension is really icky, but that's google's call.

**Comment by hthetiot** [comment]
@xtreme1397 @EricDavies I will revamp the easyrtc_sc in labs to be sure it works properly out of the box.
