### ISSUE TITLE
Firefox - failed to get access to local media

### ISSUE THREAD

**Issue by archasek** [priologic/easyrtc#280]
Hi!
Great library! But I am getting an error in FF.

https://demo.easyrtc.com/demos/demo_multiparty.html

Error messages
Failed to get access to local media. Error code was SourceUnavailableError.

FF 49.0.1 
Windows 10 64bit

The same behaviour on localhost.

**UPDATE:**
The same for Microsoft Edge 38.14393.0.0.

**Comment by hthetiot** [comment]
Work for me on FF. See screen above.
Edge support is experimental but also work forme. 

Please unless you can provide reproducible error using lib API use the forum not here
<img width="960" alt="easyrtc firefox" src="https://cloud.githubusercontent.com/assets/8635/19840169/cf70002c-9ead-11e6-8e95-9882b44f6073.png">
.

**Comment by hthetiot** [comment]
@archasek https://test.webrtc.org/

**Comment by EricDavies** [comment]
@archasek : under most operating systems, a particular camera can only be used by one application at a time. That means if you are running skype or some other type of videoconferencing software, a browser can't access the camera. Multiple instances of the same type of browser can access the same camera because its really just a single application in that case.
When it doubt, restart your machine to make sure that nothing else is using your camera.

There is also the possibility you denied access to the camera to a particular site, which tends to be an issue with chrome. 

This is really something that should be in the forums though and has been discussed a zilliions times there :-).  https://groups.google.com/forum/?fromgroups#!searchin/easyrtc/can$27t$20access$20camera%7Csort:relevance/easyrtc/62iBEzMnT4I/Dr7pdHa2ge0J

**Comment by archasek** [comment]
@EricDavies thank you for the comprehesinve reply. This was probably the reason - another browser with webrtc and camera turned on. 

> This is really something that should be in the forums though and has been discussed a zilliions times there :-). 
If I were you, I would place a BIG message with this information on the homepage and github :). 

Why not to use only github for all issues? :)

**Comment by EricDavies** [comment]
We try to use the github for things that require changes (changes or enhancements) to the code,
and the forum for stuff like "how do i ...", "why does ...", "can I send the developers a case of beer in appreciation".
It means that when we look through the github issues trying to figure what still needs to be done, it's a lot less cluttered.
As an incentive, I respond to forum questions much faster than I do to github issues because github issues tend to be longer term items.

Note you may find the following document useful: https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_debugging.md
