### ISSUE TITLE
What about minimizing sdp?

### ISSUE THREAD

**Issue by MariasStory** [priologic/easyrtc#287]
This one is somewhat old solution and may need to be updated:
https://www.npmjs.com/package/sdp-minimizer
https://github.com/fippo/sdp-minimizer

**Comment by hthetiot** [comment]
Well if you web-socket is already gzip or using spdy that not really necessary.
However it can be an opportunity to add a end to end encryption.

**Comment by MariasStory** [comment]
Its not really compression or encryption per say.

The point is that there is a static text that is necessary to have a proper sdp, but it should not necessarily be translated. So, there is a constant part of the sdp that is always transmitted for no reason.

This may have a low priority for a reasonable sdp exchange channel, but may be very useful if the sdp is transmitted using some demanding way (E-mail, chat messages, ...).

I thing it would be a good practice to have a minimal sdp translated.

**Comment by EricDavies** [comment]
If I read this right, this wouldn't have any benefit for easyrtc users/developers, but it would complicate the code and make it more prone to breaking in the future if that static portion ever got changed. Shouldn't this be something that is done by the parties that generate and consume the SDP (ie, the browsers and native code libraries) rather than those that transport it?

**Comment by MariasStory** [comment]
OK. I made a similar comment to adapter.js:
https://github.com/webrtc/adapter/issues/387
