### ISSUE TITLE
DEVELOPER_ERR "Attempt to join room %rName% which you are already in" without a callback

### ISSUE THREAD

**Issue by webolizzer** [priologic/easyrtc#295]
hello,

first, thanks for your great software!

i try to built a video app with your framework, and i have problem with this return https://github.com/priologic/easyrtc/blob/926c344f8ceb9df57170f2a78d2b152fe80a1750/api/easyrtc.js#L8018 
because after joining room by URL i.e. https://dev.videochat.red/room/English%20Room the chatroulette will try to join same room again, easy return without a callback will stop app completely. i have fixed it for me like this:

```
this.joinRoom = function(roomName, roomParameters, successCB, failureCB) {
        if (self.roomJoin[roomName]) {
            self.showError(self.errCodes.DEVELOPER_ERR, "Attempt to join room " + roomName + " which you are already in.");

            // @BUG
            // because after joining room by URL the chatroulette will try to join same
            // room again, easy return without a callback will stop app completely.
            return successCB(roomName);
        }
```

best regards 

Dennis

**Comment by webolizzer** [comment]
If someone needs, i have found a more elegant solution, because it is a very bad practice to change original framework code:

```
  /**
   * @monkey-patch for easyrtc.joinRoom
   * @author github.com/webolizzer
   */
  (function(_joinRoom) { // Cache the original method as function parameter
  
    // Redefine joinRoom method with additional "this" object
    
    easyrtc.joinRoom = function() {
    
      // get arguments
      
      var roomName = arguments[0];
      
      var successCB = arguments[2];
      
      //

      // we need a successCB, because after joining room by URL the chatroulette 
      // will try to join the same room again, easy return without a callback will stop the
      // app unnecessary completely.
      // Original Code: https://github.com/priologic/easyrtc/blob/926c344f8ceb9df57170f2a78d2b152fe80a1750/api/easyrtc.js#L8018
      
      if (easyrtc.roomJoin[roomName]) {

          return successCB(roomName);
      }
      
      // call the original method with current "this" object
      
      _joinRoom.apply(this, arguments);
      
    };
      
  })(easyrtc.joinRoom);
```

usage: simple add this snippet to your main.js file on frontend file, that's all

**Comment by EricDavies** [comment]
The philosophy of easyrtc is that it is a programmer error to try to join a room twice.
If you do, you'll get an error message displayed which is your cue to fix the error.
You can see this if you run one of our demos, connect, and then use the console to enter
    easyrtc.joinRoom('someRoom');
   easyrtc.joinRoom('someRoom');

If you want to write some application wrapper that only tries to enter a room if it hasn't already been entered, that is quite reasonable. However, I would suggest that it would be a better practice to give it a different name rather than replacing easyrtc.joinRoom because it has different semantics than easyrtc.joinRoom. Maybe something like  joinRoomIfNotInItYes .
