### ISSUE TITLE
screen-sharing demo not working (as far as I can tell)

### ISSUE THREAD

**Issue by rretter** [priologic/easyrtc#303]
Using latest general-release Chrome (57.0.2987.98) with extension "WebRTC Desktop Sharing" (v2.5, from https://chrome.google.com/webstore/detail/webrtc-desktop-sharing/nkemblooioekjnpfekmjhpgkackcajhg?utm_source=chrome-app-launcher-info-dialog).

I run the demos entitled "Screen share - Sender" (https://demo.easyrtc.com/demos/demo_screen_send.html) and "Screen Sharing Receiver" (https://demo.easyrtc.com/demos/demo_screen_receive.html) on two PCs in same local subnet.

I start sender and "connect to server", apparently successfully.

I start receiver and do the same.  Button appears on receiver "get screen of SENDERNAME" (where that is name I used on sender).  I click that button.

Prompt appears on sender side asking whether to accept or reject call.  I accept.

That's when nothing further happens.  If I choose to reject call, then receiver sees a rejection msg,  But accepting... not so much.

How can I best diagnose what's going on, or is there a more appropriate set of steps to take in trying this demo?

Thank you for any guidance you can provide.

**Comment by EricDavies** [comment]
Thank you for bringing that obsolete code to my attention.
I've just deleted it from the zombieland branch.
The old screenshare api provided by chrome didn't work very well and they superseded it with the extension based approach, which is a pain because your chrome users have to install an extension. Look at the multistream with iframe demo (which requires Muaz Khan's extension on Chrome https://chrome.google.com/webstore/detail/screen-capturing/ajhifddimkapgcifgcodmmfdlknahffk?utm_source=chrome-app-launcher-info-dialog, or works normally with firefox).

**Comment by rretter** [comment]
Thank you for making clear which demo is appropriate for me to use.  I've just tried the one you recommend and found that it works quite nicely.

Would you happen to have any clues (for me, The Clueless) about how to make the "correct" screen be shared on a multi-monitor setup ("correct" being some form of "chosen by user")?

Sorry about answering your answer with another question... though I suspect you must be used to that by now.

**Comment by EricDavies** [comment]
to the best of my knowledge, what you see is all that is possible. The dialog box is defined by chrome, we just request it to be put up and get back a value from it. You might try asking Muaz Khan, the guy who wrote the plugin; he's usually ahead of the curve with the browser api.
