### ISSUE TITLE
Install easyrtc on evennode node server

### ISSUE THREAD

**Issue by danielkuenkel** [priologic/easyrtc#409]
Hi there,

I'm experiencing different webrtc frameworks. Now i have a problem installing the easyrtc server example on my evennode server. I don't want to use the easyrtc example in a local dev environment, but in an live example. That's because my students have to be able to access it.

The details:
- uploaded the server example files to my node server. 
- the node server detects changed files and searching for any kind of start script. 
- it founds package.json and wants to start server.js 
- than the error occurs: Error: Cannot find module 'easyrtc'

The problem is, I'm not familiar with node and such things to see how I can fix the issue. I tried different things to fix the easyrtc requirement issue on the node server, but I'm stuck. I hope, anybody can help me, because I want to use easyrtc instead of the deprecated simpleRTC framework.

Best regards,
Daniel

**Comment by hthetiot** [comment]
You need at least to follow install, the example server look for easyrtc in parent folder you need to replace `require('..') by require('easyrtc) and add npm install priologic/easyrtc#master --save to your package.json if you want to use sample server.
- https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_server_install.md

Otherwise you can use docker:
- https://github.com/priologic/easyrtc/blob/00c4cdfba1ea0554ba58b81c6f9e381172ef960a/server_example/README.md

Or directly using docker commands:
> cd server_example
> docker build -t easyrtc-server -f Dockerfile 
> docker run -it -d -p 8080:8080 easyrtc-server

There is also a prebuilt image available here:
- https://hub.docker.com/r/sylaps/easyrtc-server/
> docker run -it -d -t easyrtc-server -p 8080:8080 sylaps/easyrtc-server

Live demo:
- https://easyrtc.sylaps.net

**Comment by hthetiot** [comment]
@danielkuenkel see reply above
