### ISSUE TITLE
video/audio interception

### ISSUE THREAD

**Issue by alirezag** [priologic/easyrtc#418]
Hi all, 

I'm very new to easyrtc. I'm trying to put together an mvp for a video chat app. I was wondering if it is possible to intercept video or audio on a call on the server for cloud processing (maybe some extra image processing and audio processing) before passing the video/audio to the receivers? 

Any pointers will be appreciated.

**Comment by MariasStory** [comment]
Hi @alirezag ,

In short: You should make sure that your offers exchange is not going through any relay (turn) server. This way the video/audio/data cannot be accesses/manipulated. Otherwise, you brake the connection security.

Longs answers are:
1) Normally, you should do the video/audio processing on the client side. If possible.
2) If you really have to, you could open a separate channel to the server and send the data for processing. This could be seen as a data collection and have legal implications.
3) You can brake the secure connection chain by connecting to your server and relay the connection to the client. You should not do it without informing clients. There will be simple indicators that the connection is going through you servers.

Please, check online and you will find a lot of impressive video/audio processing examples on client side.

**Comment by hthetiot** [comment]
Thx @MariasStory closing
