### ISSUE TITLE
File receiver not triggering acceptrejectchecker.

### ISSUE THREAD

**Issue by mindzombies** [priologic/easyrtc#420]
I am trying to implement file sharing in a multiparty/conference type room, and while I am able to send files by checking the debuggers and seeing that it is sending a request, what I do not get on the client end is that there is simply no trigger on file receive, nor any traces of a file request either.

If need be, I can share my code.

**Comment by hthetiot** [comment]
Can you check demo code:
- https://github.com/priologic/easyrtc/blob/master/demos/js/demo_data_channel_filesharing.js

Also can you reproduce issue here:
- https://easyrtc.sylaps.com/demos/demo_data_channel_filesharing.html

Note: Demo need input file to be more movie friendly

Note 2: you need to be connected to the peers otherwise it will come from server websocket instead of peer commection
