### ISSUE TITLE
error "attempt to connect when already connected to socket server" even if connection failed

### ISSUE THREAD

**Issue by Niklas-Peter** [priologic/easyrtc#98]
If you have unsuccessfully tried to connect to the server and if you then make a second attempt, the error message "attempt to connect when already connected to socket server" appears, although you are still unconnected. 
The problem is probably in  line 5209, where you do not check, whether the websocket is really connected. 
`if (!preallocatedSocketIo && self.webSocket)` 
However adding this check causes another error later, so you should check this.

**Comment by arunadlprivate** [comment]
I also facing same issue any fixes its very very urgent

**Comment by hthetiot** [comment]
@arunadlprivate Can you provide a jsfiddle to repro ? 
Managing the state of connection is some time not easy, you have this warning ro remind you that you have to do it properly. Also leave is not disconnect, for reminder.

**Comment by hthetiot** [comment]
@EricDavies I reply to questions cause we running in prod for a while I i got almost all possible error.
If people can repro I can help, since fixing the issue will also improve the lib or clause the issue.

**Comment by hthetiot** [comment]
@omochi can you check that change I made and let me know that you think, pls.

**Comment by omochi** [comment]
@hthetiot 
I doubt whether this commit has effect to eliminate reported issue.

First, when the error `attempt to connect when already connected to socket server` is happen, the value of `webSocket` is truthy value because of if condition.
In original code line 6328, there is 3 possible result.

- [1] `io.connect()` returns ordinary non-null object (truthy).
- [2] `io.connect()` returns null (falsy)
- [3] `io.connect()` throws exception. In this case, throwing is happen in call of `connect()` **before** assignment. So `webSocket` keeps old value. Old value is falsy because of if statement at line 6326.

Your commit changes handling flow of case [2].
But issue come from truthy `webSocket` value. this is case [1].

---

My inference of the reason of this issue is that the missing of handling `connect_failed` event from socket.io object.
https://github.com/socketio/socket.io-client/blob/0.9.17/lib/socket.js#L225
https://github.com/socketio/socket.io-client/blob/0.9.17/lib/socket.js#L247

But I don't feel sure.

**Comment by hthetiot** [comment]
@omochi socket.io 1.3.7 is the good one

I will re-recheck case [1] and case [2]
